name: .NET Core CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.xml"

    - name: Publish Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: **/test_results.xml